server:
  port: 8080
spring:
  jpa:
     show-sql: true
     hibernate:
         ddl-auto: update

  mvc:
     view:
         prefix: /WEB-INF/pages/
         suffix: .jsp

  datasource:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://106.14.119.3:3306/tao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: youqu

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
