server:
  port: 8089
  tomcat:
    max-threads: 1200
spring:
  jpa:
     database: mysql
     show-sql: true
     hibernate:
         ddl-auto: none

  redis:
      cache.clusterNodes: 192.168.101.145:6379,192.168.101.145:6380,192.168.101.145:6381,192.168.101.146:6379,192.168.101.146:6380,192.168.101.146:6381,192.168.101.147:6379,192.168.101.147:6380,192.168.101.147:6381
      cache.commandTimeout: 5000

  thymeleaf:
          mode: LEGACYHTML5
          cache: false
  kafka:
          bootstrap-servers: 192.168.103.61:9092

monitor:
  cron: 0/5 * * * * ?
  sharding-total-count: 2
  sharding-item-parameters: 0=CIB,1=ICBC
  job-description: "定时落库"
  job-parameter: "hello elastic job"

mybatis: # 注意对齐方式
  mapper-locations: classpath*:/mapping/*.xml
  type-aliases-package: com.example.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

