server:
  port: 8089
  tomcat:
    max-threads: 1200
spring:
  jpa:
     show-sql: true
     hibernate:
         ddl-auto: update
  datasource:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://106.14.119.3:3306/tao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: youqu
          tomcat:
            max-wait: 10000

  thymeleaf:
          mode: LEGACYHTML5
          cache: false

  redis:
          host: 192.168.31.19
          port: 6379
          timeout: 30
          pool:
              max-active: 80
              min-idle: 0
              max-idle: 8
              max-wait: -1
  kafka:
          bootstrap-servers: 106.14.119.3:9092

monitor:
  cron: 0/5 * * * * ?
  sharding-total-count: 2
  sharding-item-parameters: 0=CIB,1=ICBC
  job-description: "定时落库"
  job-parameter: "hello elastic job"

mybatis: # 注意对齐方式
  mapper-locations: classpath*:/mapping/*.xml
  type-aliases-package: com.example.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

